version: 2

jobs:
  test_opa:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: run opa tests
          command: docker run -v $(pwd)/terraform/cloud-platform-components/resources/opa/policies:/tmp/foobar openpolicyagent/opa test /tmp/foobar

workflows:
  version: 2
  opatest:
    jobs:
      - test_opa
