controller:
  replicaCount: 3

  # Add a snippet to each nginx server{} block, forcing HTTP->HTTPS
  # redirection regardless of Ingress rule config
  config:
    server-snippet: |
      if ($http_x_forwarded_proto != 'https') {
        return 308 https://$host$request_uri;
      }

  # nginx-ingress's ServiceType=LoadBalancer by default, so we're mainly
  # configuring an ELB here
  service:
    annotations:
      # Have `external-dns` create a Route53 record pointing to this ELB
      external-dns.alpha.kubernetes.io/hostname: "*.apps.cloud-platform-test-1.k8s.integration.dsd.io"

      # Attach pre-existing ACM cert
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:eu-west-1:926803513772:certificate/f6a09836-131b-40a6-b668-8e678b962b42"

      # Enable ELB SSL protocol on port 443 only (default is all ports)
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"

      # Use HTTP protocol for instance traffic, as we're terminating on the ELB
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"

    # Direct ELB HTTPS traffic to instance HTTP port, as we're terminating on
    # the ELB
    targetPorts:
      https: 80

    # Preserve source IP address
    externalTrafficPolicy: "Local"

# Create RBAC role with required perms for nginx-ingress's ServiceAccount
rbac:
  create: true
  serviceAccountName: default
