apiVersion: v1
appVersion: "0.1.0"
description: A Helm chart for prometheus ecr-exporter
name: prometheus-ecr-exporter
version: 0.1.0
home: https://github.com/ministryofjustice/prometheus_ecr_exporter
sources:
- https://github.com/ministryofjustice/prometheus_ecr_exporter
keywords:
- aws
- ecr
- prometheus
- exporter
